name: Build APK

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: refs/tags/1.14.4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'gradle'
    - name: Download dependencies
      run: ./gradlew androidDependencies
    - name: Build release APK
      run: ./gradlew assembleRelease
      env:
        APPID: de.szalkowski.activitylauncher.oss
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: release.apk
        path: app/build/outputs/apk/oss/release/app-oss-release.apk
